mode: black-box
target: http://192.168.1.130:3000
generated_at: '2025-12-26T22:41:50.892Z'
reconnaissance:
  aggressive_crawling: true
  javascript_analysis: true
  api_schema_discovery: true
  max_depth: 3
  timeout: 30
authentication: null
rules:
  avoid: []
  focus:
    - description: Prioritize API endpoints
      type: path_prefix
      url_path: /api
